### ISSUE TITLE
Specific queries re transtional data

### ISSUE THREAD

**Issue by pbrockPhas** [sfg-taxonpages/phasmida#10]
- [x] 1)	https://sfg-taxonpages.github.io/phasmida/#/otus/856437/overview for Trachythorax conspersus in TW shows Calvisia atrosignata Brunner von Wattenwyl, 1893 as a synonym. In old PSF, the valid species for atrosignata is correctly recorded as Trachythorax maculicollis. Possibly because of changes over the years, the software picked this up as a synonym of conspersus, in error. This may also link with 3 x ‘unavailable or invalid’ references in citations for conspersus.
- [x] 2)	https://sfg-taxonpages.github.io/phasmida/#/otus/851143/overview  for Agathemerodea in TW is an error. A former suborder Agathemerodea is correctly listed as nomen dubia in old PSF, See that website for references (the family Agathemeridae and associated species is, however, correct in TW i.e. within Pseudophasmatoidea).
	Guidance needed to correct the above please

**Comment by debpaul** [comment]
number 2 above needs to be _nomen dubia_. We worked through this at the open session on 18 October 2023.

**Comment by mjy** [comment]
Concensus is that 1) could use then envisioned "merge" tool.

**Comment by pbrockPhas** [comment]
switched Pt 1 as synonym of the right species - will sort out the many references later!
