### ISSUE TITLE
Merge irregulariterdentata into single taxon name [Was: Combination queries in citations]

### ISSUE THREAD

**Issue by pbrockPhas** [sfg-taxonpages/phasmida#11]
- [x] 1)	I want to add a reference in Cai, 1987 to Phraortes bicolor in TW i.e. https://sfg-taxonpages.github.io/phasmida/#/otus/855083/overview  the reference in Cai p. 27 is to Staelonchodes bicolor – this combination is not in TW.
- [x] 2)	Ditto Cai p. 27 Phraortes chinensis https://sfg-taxonpages.github.io/phasmida/#/otus/855078/overview the reference in Cai p. 27 is to Staelonchodes chinensis – this combination is not in TW.
- [x] 3)	Ditto Cai p. 28 Ramulus mikado https://sfg-taxonpages.github.io/phasmida/#/otus/933360/overview  - I want to add the citation to the synonym listed in Cai, but the reference is to Baculum irregulariterdentata (only Baculum irregulariterdentatum shown as a combination in TW).
- [x] 4)	Ditto Cai p. 28 Entoria ishigakeiensis https://sfg-taxonpages.github.io/phasmida/#/otus/853636/overview the reference in Cai p. 27 is to Entoria isiigakeiensis – this combination [typo] is not in TW.
- [x] 5)	Another citation query has also cropped up - https://sfg.taxonworks.org/tasks/nomenclature/by_source?source_id=179405 does not show the author in citations in TW i.e. Passerin d´Entreves, P.   this may be due to the software not understanding what the surname is, as it is lengthy! Also in OSF, as Passerin d'Entrèves so I need to adjust the spelling. I still have an issue o/s on authors issue #8, expect the remedy may be similar.
	Guidance needed to correct the above please

**Comment by pbrockPhas** [comment]
No.5 corrected during zoom meeting 18 October

**Comment by mjy** [comment]
Outstanding 3 requires/blocked by availability of merge function.

**Comment by pbrockPhas** [comment]
Sorted No.3 - or will do once I add some references back on.
