### ISSUE TITLE
Duplicated subspecies

### ISSUE THREAD

**Issue by pbrockPhas** [sfg-taxonpages/phasmida#12]
NOT URGENT – Matt, as discussed to action after the Taxon Works Conference! Note – all combinations used in old PSF are correct. In TW in the next 12 examples, the higher number for each taxon has the correct species ending, but the lower number has various citations, images etc. and is obviously needed. However during the transition TW has changed species name endings on various occasions, so some of these are incorrect…  

- [x] Bacillus rossius rossius 936797 (species described as Mantis rossia), 852085 (described as Mantis rossia; includes also the synonyms and numerous citations, which have correct species endings).

- [x] Stheneboea bifoliata bifoliata  936829 (species described by Haan, 1842 as Phasma (Acanthoderus) bifoliatum shown correctly), 855188 (description by de Haan, 1842 shown as Phasma bifoliata in error; includes a synonym and several other citations (correct species endings).

- [x] Psudophasma rugosum rugosum  936785 (species described by Redtenbacher, 1906 as Anisomorpha rugosa shown correctly), 855188 (description by Redtenbacher, 1906 shown as Anisomorpha rugosum in error; includes several other citations (correct species endings, except Brock 1998 should show Anisomorpha rugosa NOT Anisomorpha rugosum).

- [x] Leiophasma nigrotuberculatum nigrotuberculatum  936802 (species described by Redtenbacher, 1906 as Orobia nigrotuberculata shown correctly), 852481 (description by Redtenbacher, 1906 shown as Orobia nigrotuberculatum in error; includes several other citations (correct species endings).

- [x] Spinacepherus verrucosus verrucosus 936830 (species described by H, 1842 as Phasma (Acanthoderus) verrucosum shown correctly), 855274 (description by Haan, 1842  shown as Phasma verrucosus in error; includes several other citations (correct species endings).

- [x] Acacus sarawacus sarawacus 936834 (species described by Westwood, 1859 as Bacteria sarawaca shown correctly), 855543 (description by Westwood, 1859 shown as Bacteria sarawacus in error; includes many other citations (correct species endings).

- [x] Qiongphasma bispinosum bispinosum 936833 (species described by Ho, 2013 as Qiongphasma bispinosus bispinosus but incorrectly stated in 936833 as Qiongphasma bispinosum bispinosus), 855543 (description by Westwood, 1859 shown as Qiongphasma [SPECIES NOT SPECIFIED] bispinosum in error; includes other citations (correct species endings). In addition the edit page on this is way over to the left virtually out of sight i.e. the only one left with a '[SPECIES NOT SPECIFIED]' I could not edit - it would probably be difficult without the correct species ending as well.

- [x] Centrophasma hadrillum hadrillum 936837 (species described by Westwood, 1859 as Lopaphus hadrillus shown correctly), 855715 (description by Westwood, 1859 shown as Lopaphus hadrillum in error; includes several other citations (correct species endings, except that Kirby 1904 should read Lopaphus hadrillus).

- [x] Centrophasma spinosum spinosum 936839 (species described by Saussure, 1868 as Lopaphus spinosus shown correctly), 855724 (description by Saussure, 1868 shown as Lopaphus spinosum in error; includes several other citations (correct species endings, except that Saussure 1860 should read Lopaphus spinosus).

- [x] Orthonecroscia fuscoannulata fuscoannulata  936844 (species described by Haan, 1842 as Phasma (Necroscia) fuscoannulatum  shown correctly), 856102 (description by Haan, 1842 shown as Phasma fuscoannulata in error; includes several other citations (correct species endings).

- [x] Oxyartes despectus despectus  936846 (species described by Westwood, 1848 as Phasma (Acanthoderus) despectum shown correctly), 856158 (description by Westwood, 1848 shown as Phasma despectus in error; includes several other citations (correct species endings).

- [x] Orthostheneboea exotica exotica 936847 (species described by Brunner, 1907 as Promachus exoticus  shown correctly), 856558 (description by Brunner, 1907 shown as Promachus exotica in error; includes several other citations (correct species endings, except that Carl 1913 should read Promachus exoticus).

Another issue with a subspecies is this one for 

- [x] Hermagoras foliopeda foliopeda should not exist https://sfg-taxonpages.github.io/phasmida/#/otus/854919/overview  as there are no longer other subspecies. It could not be deleted in old PSF....

Also added to this list 9 Nov and only partly solved by me 3 Jan

- [x] Tried to delete Brasidas foveolatus (duplicate) https://sfg.taxonworks.org/tasks/nomenclature/browse?taxon_name_id=960081 but leaves it as okay in TP, but still on the system, hence it reads 11 Brasidas species instead of 10.

**Comment by proceps** [comment]
in my oppinion, Mantis rossia should be treated as a noun, not an adjective

**Comment by proceps** [comment]
Please double check synonymy and citations for Hermagoras foliopeda
