### ISSUE TITLE
Editing Taxon Page misaligned

### ISSUE THREAD

**Issue by pbrockPhas** [sfg-taxonpages/phasmida#20]
New taxa in Brock & Hasenpusch, 2007 all have much of the main Edit Taxon Page screen misaligned i.e.
- [ ] _Cornicandovia_ https://sfg.taxonworks.org/tasks/nomenclature/new_taxon_name?taxon_name_id=963999
- [ ]  _Candovia robinsoni_ https://sfg.taxonworks.org/tasks/nomenclature/new_taxon_name?taxon_name_id=963982
- [ ] _Austrosipyloidea_ https://sfg.taxonworks.org/tasks/nomenclature/new_taxon_name?taxon_name_id=963995
- [ ] _Sipyloidea brevicerci_ https://sfg.taxonworks.org/tasks/nomenclature/new_taxon_name?taxon_name_id=963914
- [ ] _Sipyloidea garradungensis_ https://sfg.taxonworks.org/tasks/nomenclature/new_taxon_name?taxon_name_id=963915
- [ ] _Sipyloidea larryi_ https://sfg.taxonworks.org/tasks/nomenclature/new_taxon_name?taxon_name_id=963916
- [ ] _Sipyloidea lewisensis_ https://sfg.taxonworks.org/tasks/nomenclature/new_taxon_name?taxon_name_id=963916
- [ ] _Sipyloidea rentzi_ https://sfg.taxonworks.org/tasks/nomenclature/new_taxon_name?taxon_name_id=963918
- [ ] _Sipyloidea whitei_ https://sfg.taxonworks.org/tasks/nomenclature/new_taxon_name?taxon_name_id=963919
- [ ] _Spinosipyloidea_ https://sfg.taxonworks.org/tasks/nomenclature/new_taxon_name?taxon_name_id=964001
- [ ] _Spinosipyloidea doddi_ https://sfg.taxonworks.org/tasks/nomenclature/new_taxon_name?taxon_name_id=964002
- [ ] _Pachymorpha spinosa_ https://sfg.taxonworks.org/tasks/nomenclature/new_taxon_name?taxon_name_id=961608
- [ ] _Davidrentzia_ https://sfg.taxonworks.org/tasks/nomenclature/new_taxon_name?taxon_name_id=961703
- [ ] _Davidrentzia valida_ https://sfg.taxonworks.org/tasks/nomenclature/new_taxon_name?taxon_name_id=961704
- [ ] _Micropodacanthus_ https://sfg.taxonworks.org/tasks/nomenclature/new_taxon_name?taxon_name_id=960948
- [ ] _Micropodacanthus mouldsi_ https://sfg.taxonworks.org/tasks/nomenclature/new_taxon_name?taxon_name_id=960949
- [ ] _Micropodacanthus sztrakai_ https://sfg.taxonworks.org/tasks/nomenclature/new_taxon_name?taxon_name_id=960950
- [ ] _Paratropidoderus_ https://sfg.taxonworks.org/tasks/nomenclature/new_taxon_name?taxon_name_id=960952
- [ ] _Paratropidoderus spinosus_ https://sfg.taxonworks.org/tasks/nomenclature/new_taxon_name?taxon_name_id=960953
- [ ] _Podacanthus keyi_ https://sfg.taxonworks.org/tasks/nomenclature/new_taxon_name?taxon_name_id=960926
ONLY SAMPLED SOME TAXA, BUT ALSO A PROBLEM IN SOME OTHER PAPERS, SO THIS MAY BE FAIRLY EXTENSIVE. THE SAME PROBLEM NOTED WITH:
- [ ] _Pachymorpha pearsoni_ https://sfg.taxonworks.org/tasks/nomenclature/new_taxon_name?taxon_name_id=961610
- [ ] _Onchestus ripperae_ https://sfg.taxonworks.org/tasks/nomenclature/new_taxon_name?taxon_name_id=960782
- [ ] _Xeroderus_ https://sfg.taxonworks.org/tasks/nomenclature/new_taxon_name?taxon_name_id=961035
- [ ] _Xeroderus conlei_ https://sfg.taxonworks.org/tasks/nomenclature/new_taxon_name?taxon_name_id=961035
- [ ] _Parapodacanthus ailaketoeae_ https://sfg.taxonworks.org/tasks/nomenclature/browse?taxon_name_id=960947

**Comment by debpaul** [comment]
@pbrockPhas please perhaps a screenshot?

for _Cornicandovia_ inside TaxonWorks https://sfg.taxonworks.org/tasks/nomenclature/new_taxon_name?taxon_name_id=963999 I see the following (screenshot).
Is that what you mean by "misaligned?"

![image](https://github.com/sfg-taxonpages/phasmida/assets/2990155/5e34e828-260f-4720-bf23-67590bdbe492)

**Comment by mjy** [comment]
@jlpereira I think this is because of long URLs, Paul can confirm maybe.

<img width="1349" alt="Screenshot 2023-11-14 at 3 43 33 PM" src="https://github.com/sfg-taxonpages/phasmida/assets/22600/0348fbf8-cedf-448f-8b67-826fb6dfa793">

**Comment by jlpereira** [comment]
Yes, we have to break the links there. I will fix it

**Comment by jlpereira** [comment]
Fixed, @pbrockPhas you will see the change on the next update.

**Comment by pbrockPhas** [comment]
Thanks, look forward to seeing the change as I could not see the screen to enter e.g. etymology!
