### ISSUE TITLE
Editing - issue linking to replacement name

### ISSUE THREAD

**Issue by pbrockPhas** [sfg-taxonpages/phasmida#4]
Struggling with linking a replacement name. The paper by Villet (2023) has been added to the database, also a new genus Bostranova, which replaces Bostra. A lot of species should automatically become new combinations. Attempted to use the manual, but expect that I have entered detail(s) incorrectly somewhere. Help!
**-- added to the sheet to discuss on Wednesday 27 September via zoom**

**Comment by proceps** [comment]
Add a new genus name in the database, in this case Bostranova. Than go to edit the synonym name, in this case Bostra, and add a relationship (Replaced by). Afther that you will have a table dialog on the page, that will suggest to move all species of Bostra to Bostranova. This will change the parrent of each included species. After than, I usually go to edit each individual species to create a new combination. I create the combinations with individual citations.

**Comment by pbrockPhas** [comment]
I clearly went through a wrong route at the outset as I had no table dialog and cannot find that now. Will probably need help at the meeting on 27th - Bostra Status box shows valid, unavailable and homonym. In Relationship for Bostra it does state: replaced by Bostranova. Thies has had a look as well and neither of us can link it to the Bostra species. I will look again later today, but do not hold out much hope of getting it right!
