### ISSUE TITLE
Editing - Adding references

### ISSUE THREAD

**Issue by pbrockPhas** [sfg-taxonpages/phasmida#6]
Attempted to add Luna et al 2023 (Mexican phasmids) on PSF - the source is included but only _Anisomorpha paromalus_ is readily visible. The other citations to species e.g. _Anisomorpha buprestoides_ appear as OTUs. This does not look right to me, as this does not show in the references list. Would you mind having a look and advise, possibly I misinterpreted the instruction video.

One oddity is _Metriophasma_ (_Metriophasma_) _iphicles_ - it appears as that on PSF, but the author just used _Metriophasma_ _iphicles_. I could not find a way for this to show as just _Metriophasma iphicles_...

Apologies for the very basic issue here - Trying to get to grips with the software, at least I added Mexico to the map for iphicles!

**Comment by mjy** [comment]
No need to apologize, there is a lot to dive into.  

If you want to represent the name as it appears in the literature then you need to create a Combination for that name, and use that OTU to record the distribution.   Browsing an OTU automatically combines all the related OTU concepts into a single cohesive view.

**Comment by pbrockPhas** [comment]
Noted, thanks. Would you mind seeing if the Luna ref. looks okay for, say, _Anisomorpha paromalus_ and _Anisomorpha buprestoides_? I think the latter (and others) may be incorrect, particularly as it does not seem to show for the latter species, except via a search on the source. There is a lot to learn and I will have to watch the videos in the right sequence; getting confused.

**Comment by pbrockPhas** [comment]
Matt  Thanks, clarified during the zoom meeting. I made a basic mistake in adding some citations to OTUs, instead of through main nomenclature...
