### ISSUE TITLE
Question - specific queries, mainly maps

### ISSUE THREAD

**Issue by pbrockPhas** [sfg-taxonpages/phasmida#9]
Whilst editing citations and maps, I have encountered specific issues which I cannot readily solve:
* [x] Phalces brevis https://sfg-taxonpages.github.io/phasmida/#/otus/852112/overview - the de Haan reference appears at the end of the alphabetical list (and elsewhere in the database. I note included as Haan in OSF, so possibly just need to change the author’s name – but see Author Query #8, guidance needed).
* [x]  Paracandovia longipes https://sfg-taxonpages.github.io/phasmida/#/otus/856723/overview - need to remove Western Australia from the map (= PLT misidentified as longipes).
* [x]  P. peridromes https://sfg-taxonpages.github.io/phasmida/#/otus/933081/overview - need to remove Queensland (assertive distribution) from the map (error). Tried deleting it but unsuccessful.
* [x]  Similar story with _Bacillus rossius rossius_ https://sfg-taxonpages.github.io/phasmida/#/otus/852085/overview  where I added assertive distribution thinking it was for another Bacillus sp., pressing delete did not remove, for example, Israel.
* [x]  _Dryococelus australis_ https://sfg-taxonpages.github.io/phasmida/#/otus/853177/overview - the map for Australia (related to type data of a synonym) ideally needs removing, as it should just show Lord Howe Island, perhaps Balls Pyramid, if there is a map for that!
* [x]  _Tropidoderus rhodomus_ https://sfg-taxonpages.github.io/phasmida/#/otus/853412/overview - Philippines needs removing (related to type data of a synonym, thought to be ficticious).

**Comment by mjy** [comment]
Re the AD removal. There is a pending fix for destroying AssertedDistributions from the OTU radia coming shortly, that might be one of the issues (removing AD).  It could be destroyed, curently, from Show or Navigator though.

**Comment by pbrockPhas** [comment]
Just tried with https://sfg.taxonworks.org/tasks/otus/browse?otu_id=856722  (peridromes), so Queenland no longer shows in the 'Asserted Distribution' section but still shows on the map! Looks like I may have to wait until the fix appears.

**Comment by jrflood** [comment]
So looking at the specimens inSFG-TW for P. longipes I see Australia, Bowen (as Port Denison) as the locality.  But Port Denison is on the west coast in Western Australia and Bowen is in Queensland (which is what the SF site says).  But the fact that 3 of the 4 specimens indicate Port Denison might be why Western Australia is present.

**Comment by pbrockPhas** [comment]
These notes from my 2022 paper Forni et al. clarifies the position: "Paracandovia longipes (Brunner, 1907) [Bowen Stick insect] stat. rev., comb. nov.: Queensland [lectotype locality Bowen = sample Candovia sp. I from Dingo]. The paralectotype from Western Australia is a misidentified female of Echetlus peristhenes (Westwood, 1859) [removed from synonymy with Candovia peridromes (Westwood, 1859)]."
So I appreciate why Western Australia appears on the map fr longipes, but wonder whether there is some mechanism to override it? Obviously it still needs the paralectotype linked with longipes (there will be various case in SF databases where paralectotypes are misidentified). 

Incidentally Rich, you may have noticed that I went through and updated maps for mainly Australian species. Making progress....

**Comment by pbrockPhas** [comment]
Spending some time on distribution maps now - coming across various oddities, examples include genera with odd maps, a simple example here: https://sfg-taxonpages.github.io/phasmida/#/otus/852173/overview Ulugurucharax (shows only Madagascar), whereas the only genus correctly shows 'Africa'....I will send a list of oddities in later. One species so far Agathemera mesoauriculae https://sfg-taxonpages.github.io/phasmida/#/otus/852062/overview has no type data (several on old PSF software), first I have seen where the type data failed to transfer, but early days on the assessment yet. Certainly the case that several genera have maps bearing little resemblance to species data -- yet others are spot on.

**Comment by pbrockPhas** [comment]
Following 1 Nov nomenclature meeting, now had the knowledge to resolve pt. 6 - and it worked!
